### ISSUE TITLE
TypeError: 'range' object does not support item assignment

### ISSUE THREAD

**Issue by YangSN0719** [bojone/flow#7]

**Comment by YangSN0719** [comment]
(flow) [409@mu01 flow-master]$ python glow.py
Using TensorFlow backend.
WARNING:tensorflow:From /home/409/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
File "glow.py", line 105, in 
x = permute(x)
File "/home/409/anaconda3/envs/flow/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in _call_
self.build(unpack_singleton(input_shapes))
File "/home/409/ysn/flow-master/flow_layers.py", line 31, in build
trainable=False)
File "/home/409/anaconda3/envs/flow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "/home/409/anaconda3/envs/flow/lib/python3.6/site-packages/keras/engine/base_layer.py", line 249, in add_weight
weight = K.variable(initializer(shape),
File "/home/409/ysn/flow-master/flow_layers.py", line 37, in random_initializer
np.random.shuffle(idxs)
File "mtrand.pyx", line 4859, in mtrand.RandomState.shuffle
File "mtrand.pyx", line 4862, in mtrand.RandomState.shuffle
TypeError: 'range' object does not support item assignment
Ask for your help here,thanks! @bojone

**Comment by YangSN0719** [comment]
![错误处理](https://user-images.githubusercontent.com/44280931/56208212-2c327f80-6083-11e9-97a1-c2f3f1cc94e4.png)

**Comment by YangSN0719** [comment]
### TypeError: 'range' object does not support item assignment处理方法 
vectorsum.py
#!/usr/bin/env/python
import sys
from datetime import datetime
import numpy as np

# def numpysum(n):
#     a = np.arange(n) ** 2
#     b = np.arange(n) ** 3
#     c = a + b
#     return c

def pythonsum(n):
    a = range(n)
    b = range(n)
    c = []
    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c

size = int(sys.argv[1])
print (size)

start = datetime.now()
c = pythonsum(size)
delta = datetime.now() - start
print ("The last 2 elements of the sum", c[-2:])
print ("PythonSum elapsed time in microseconds", delta.microseconds)
# start = datetime.now()
# c = numpysum(size)
# delta = datetime.now() - start
# print ("The last 2 elements of the sum", c[-2:])
# print ("NumPySum elapsed time in microseconds", delta.microseconds)
----------------------------------------------------------------------------
运行结果：
D:\>python vectorsum.py 1000
1000
Traceback (most recent call last):
File "vectorsum.py", line 26, in <module>
c = pythonsum(size)
File "vectorsum.py", line 17, in pythonsum
a[i] = i ** 2
TypeError: 'range' object does not support item assignment
----------------------------------------------------------------------------------------
将pythonsum函数修改如下： 
def pythonsum(n):
    a = list(range(n))
    b = list(range(n))
    c = []
    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c



运行正常，通过
-----------------------------------------------------------
